import os
import httpx  
from contextlib import asynccontextmanager
from fastapi import FastAPI, HTTPException, status
from fastapi.middleware.cors import CORSMiddleware
from motor.motor_asyncio import AsyncIOMotorClient
from pydantic import BaseModel, EmailStr
from database import UserModel

# --- CONFIGURATION ---
MONGODB_URL = os.getenv("MONGODB_URL", "mongodb+srv://rinshid:rinshid*vp%23@cluster0.uuvk41c.mongodb.net/?appName=Cluster0")
DB_NAME = "campus_trade_db"

# --- AI CONFIGURATION ---
GEMINI_API_KEY = "AIzaSyDqYdWEiVfvTikw4Fb19f5pKudsNwv6iOA"  # <--- YOUR VIP PASS

# --- LIFESPAN (Database Connection) ---
@asynccontextmanager
async def lifespan(app: FastAPI):
    app.mongodb_client = AsyncIOMotorClient(MONGODB_URL)
    app.mongodb = app.mongodb_client[DB_NAME]
    print("Connected to MongoDB")
    yield
    app.mongodb_client.close()
    print("Disconnected from MongoDB")

app = FastAPI(lifespan=lifespan)

# --- CORS SHIELD ---
app.add_middleware(
    CORSMiddleware,
   allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# --- SCHEMAS ---
class UserCreate(BaseModel):
    name: str
    college_email: EmailStr

class Item(BaseModel):
    title: str
    description: str
    price: float
    seller_email: EmailStr 

class AIGenerate(BaseModel):
    title: str


# --- ROUTES ---

@app.get("/health")
async def health_check():
    return {"status": "ok"}


@app.post("/api/register", status_code=status.HTTP_201_CREATED)
async def register_user(user_data: UserCreate):
    if not user_data.college_email.endswith("@tkmce.ac.in"):
        raise HTTPException(status_code=400, detail="Only @tkmce.ac.in email addresses are allowed.")

    existing_user = await app.mongodb["users"].find_one({"college_email": user_data.college_email})
    if existing_user:
        raise HTTPException(status_code=400, detail="User with this email already exists.")

    new_user = UserModel(
        name=user_data.name,
        college_email=user_data.college_email,
        is_verified=False,
        bank_details_linked=False
    )

    user_dict = new_user.model_dump(by_alias=True, exclude={"id"})
    result = await app.mongodb["users"].insert_one(user_dict)
    
    return {"id": str(result.inserted_id), "message": "User registered successfully"}


@app.post("/api/items", status_code=status.HTTP_201_CREATED)
async def create_item(item_data: Item):
    item_dict = item_data.model_dump()
    result = await app.mongodb["items"].insert_one(item_dict)
    return {"message": "Item posted successfully!", "item_id": str(result.inserted_id)}


@app.get("/api/items", status_code=status.HTTP_200_OK)
async def get_all_items():
    items_cursor = app.mongodb["items"].find()
    items_list = await items_cursor.to_list(length=100)
    for item in items_list:
        item["_id"] = str(item["_id"])
    return items_list


# <--- THE UPGRADED GEMINI 2.0 FLASH ROUTE --->
# <--- THE GRACEFUL FALLBACK AI ROUTE --->
@app.post("/api/generate-description")
async def generate_ai_description(data: AIGenerate):
    try:
        prompt = f"Act as an expert marketer. Write a highly persuasive, 2-sentence sales description for a college student selling their '{data.title}'. Do not include the price, just make it sound like an amazing deal for another engineering student."
        
        url = f"https://generativelanguage.googleapis.com/v1/models/gemini-2.0-flash:generateContent?key={GEMINI_API_KEY}"
        payload = {"contents": [{"parts": [{"text": prompt}]}]}
        
        async with httpx.AsyncClient() as client:
            response = await client.post(url, json=payload, timeout=5.0)
            response_data = response.json()
            
        if "error" in response_data:
            raise Exception(response_data["error"]["message"])
            
        magic_text = response_data["candidates"][0]["content"]["parts"][0]["text"]
        return {"description": magic_text.strip()}
        
    except Exception as e:
        # If Google blocks us (Quota Limit, 404, 429), we catch it here!
        print(f"\n[SERVER NOTE] Google API failed: {e}")
        print("[SERVER NOTE] Executing Graceful Fallback for user...\n")
        
        # We seamlessly return a backup description so the frontend doesn't crash
        fallback_text = f"✨ [Generated by Backup System] Perfectly suited for engineering students! This {data.title} is in excellent condition, highly reliable, and ready to help you crush your college assignments."
        
        return {"description": fallback_text}
        # --- STARTUP COMMAND FOR RENDER ---
if __name__ == "__main__":
    import uvicorn
    # Render provides a dynamic PORT environment variable we must use
    port = int(os.environ.get("PORT", 8000))
    uvicorn.run(app, host="0.0.0.0", port=port)